# Generated by Django 3.2.2 on 2021-05-06 15:40

from django.db import migrations, models
import uuid
import web.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('room_id', models.CharField(default=web.models.set_default_random_room_id, max_length=7, primary_key=True, serialize=False)),
                ('meeting_id', models.UUIDField(default=uuid.uuid4)),
                ('room_name', models.CharField(default=web.models.set_default_random_room_name, max_length=100)),
                ('pin', models.IntegerField(default=web.models.set_default_random_pin)),
                ('joins', models.SmallIntegerField(default=web.models.set_default_joins)),
                ('status', models.CharField(choices=[('running', 'Meeting is currently running'), ('finished', 'Meeting has been finished')], default='running', max_length=10)),
                ('end_of_life', models.DateTimeField(default=web.models.set_default_eol, editable=False)),
            ],
        ),
    ]
